version: '3.4'

services:
  fastbuild:
    build:
        context: .
        dockerfile: ./Dockerfile
    stdin_open: true 
    tty: true   
    volumes:
      - '.:/usr/src/test:rw'
    command: /bin/bash